# Generated by Django 5.1.1 on 2025-08-14 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Quản lý User',
                'verbose_name_plural': 'Quản lý User',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='SuperUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Quản lý Admin',
                'verbose_name_plural': 'Quản lý Admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Quản lý User'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Gói Premium'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn Premium'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm nâng quyền'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_users', to=settings.AUTH_USER_MODEL, verbose_name='Người nâng quyền'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tham gia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Quyền truy cập Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tên đăng nhập'),
        ),
    ]
