# Generated by Django 4.2.21 on 2025-07-05 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_cluster_code', models.CharField(max_length=50)),
                ('selected_cluster_name', models.CharField(max_length=100)),
                ('answers', models.JSONField(default=list)),
                ('skill_scores', models.JSONField(default=dict)),
                ('readiness_score', models.PositiveIntegerField(default=0)),
                ('analysis_html', models.TextField()),
                ('recommended_actions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_university_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài đánh giá kỹ năng',
                'verbose_name_plural': 'Bài đánh giá kỹ năng',
                'ordering': ['-created_at'],
            },
        ),
    ]
