# Generated by Django 5.1.1 on 2025-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuniversity',
            name='detailed_analysis_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
