# Generated by Django 5.1.1 on 2025-08-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_highschool', '0004_resultfeedbackhighschool_and_more'),
        ('quiz_university', '0002_quizuniversity_detailed_analysis_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFeedbackUniversity',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback (SV)',
                'verbose_name_plural': 'Feedback (SV)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz_highschool.resultfeedback',),
        ),
    ]
