# Generated by Django 4.2.21 on 2025-07-02 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHighschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=list)),
                ('cluster_percentages', models.JSONField(default=dict)),
                ('top_cluster_code', models.CharField(max_length=20)),
                ('top_cluster_name', models.CharField(max_length=100)),
                ('top_percentage', models.FloatField()),
                ('second_cluster_code', models.CharField(max_length=20)),
                ('second_cluster_name', models.CharField(max_length=100)),
                ('second_percentage', models.FloatField()),
                ('top_analysis_html', models.TextField()),
                ('second_analysis_html', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_highschool_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
