# Generated by Django 5.1.1 on 2025-08-09 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quiz_highschool', '0002_resultfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resultfeedback',
            name='unique_user_feedback_per_quizobject',
        ),
        migrations.RenameIndex(
            model_name='resultfeedback',
            new_name='idx_ct_obj',
            old_name='quiz_highsc_content_d4e481_idx',
        ),
        migrations.RenameIndex(
            model_name='resultfeedback',
            new_name='idx_moderation_stats',
            old_name='quiz_highsc_approve_d60957_idx',
        ),
        migrations.AddIndex(
            model_name='resultfeedback',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='idx_owner_ct_obj'),
        ),
    ]
