# Generated by Django 5.1.1 on 2025-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_highschool', '0003_remove_resultfeedback_unique_user_feedback_per_quizobject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFeedbackHighschool',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback (HS)',
                'verbose_name_plural': 'Feedback (HS)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz_highschool.resultfeedback',),
        ),
        migrations.AlterModelOptions(
            name='quizhighschool',
            options={'verbose_name': 'Bài test HS', 'verbose_name_plural': 'Bài test HS'},
        ),
        migrations.AlterModelOptions(
            name='resultfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phản hồi kết quả', 'verbose_name_plural': 'Phản hồi kết quả'},
        ),
        migrations.AlterField(
            model_name='resultfeedback',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đã duyệt'),
        ),
        migrations.AlterField(
            model_name='resultfeedback',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Công khai'),
        ),
    ]
