# Generated by Django 4.2.21 on 2025-08-01 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('trend_score', models.FloatField(default=0)),
                ('job_growth', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TopIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_count', models.IntegerField(default=0)),
                ('previous_job_count', models.IntegerField(default=0)),
                ('job_growth_percent', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
