# Generated by Django 4.2.21 on 2025-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
