# Generated by Django 4.2.21 on 2025-08-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
