# Generated by Django 4.2.21 on 2025-08-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_transaction_payment_link_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='has_used_trial',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='trial_end',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='trial_start',
        ),
    ]
